[package]
name = "vectorg-engine-benchmarks-2d"
version = "0.1.0"
authors = ["Sébastien Crozet <sebcrozet@dimforge.com>"]
edition = "2021"
rust-version = "1.82"

[features]
parallel = ["vectorg-engine-2d/parallel", "vectorg-engine-testbed-2d/parallel"]
simd-stable = ["vectorg-engine-2d/simd-stable"]
simd-nightly = ["vectorg-engine-2d/simd-nightly"]
other-backends = ["vectorg-engine-testbed-2d/other-backends"]
enhanced-determinism = ["vectorg-engine-2d/enhanced-determinism"]

[dependencies]
rand = "0.8"
Inflector = "0.11"

[dependencies.vectorg-engine-testbed-2d]
path = "../crates/vectorg-engine-testbed-2d"

[dependencies.vectorg-engine-2d]
path = "../crates/vectorg-engine-2d"

[[bin]]
name = "all_benchmarks2"
path = "./all_benchmarks2.rs"