[package]
name = "vectorg-engine-benchmarks-3d"
version = "0.1.0"
authors = ["Sébastien Crozet <sebcrozet@dimforge.com>"]
edition = "2021"
rust-version = "1.82"

[features]
parallel = ["vectorg-engine/parallel", "vectorg-engine-testbed-3d/parallel"]
simd-stable = ["vectorg-engine/simd-stable"]
simd-nightly = ["vectorg-engine/simd-nightly"]
other-backends = ["vectorg-engine-testbed-3d/other-backends"]
enhanced-determinism = ["vectorg-engine/enhanced-determinism"]

[dependencies]
rand = "0.8"
Inflector = "0.11"

[dependencies.vectorg-engine-testbed-3d]
path = "../crates/vectorg-engine-testbed-3d"

[dependencies.vectorg-engine]
path = "../crates/vectorg-engine"

[[bin]]
name = "all_benchmarks3"
path = "all_benchmarks3.rs"
